[package]
name = "merge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
serde = {version = "1.0.194", features = ["derive"]}
serde_json = "1.0.110"
strcursor = "0.2.5"
thiserror = "1.0.56"
proc = {version = "*", path = "../proc"}
